//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("carrental-backend-email-otp")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Backend")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+507e609879bf747e0cc46a178ce0fda7ecbc67d2")]
[assembly: System.Reflection.AssemblyProductAttribute("Backend")]
[assembly: System.Reflection.AssemblyTitleAttribute("Backend")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Backend.Tests")]

// Generated by the MSBuild WriteCodeFragment class.

